### ISSUE TITLE
Can not compile with V4.2.0

### ISSUE THREAD

**Issue by ChetManley94** [OpenTOPAS/OpenTOPAS#222]
I am downloading OpenTOPAS for the first time & have followed the quick start guide line-by-line. When attempting to compile OpenTOPAS (step 8) with:

 _cmake ../OpenTOPAS -DCMAKE_INSTALL_PREFIX=../OpenTOPAS-install

 make -j10 install_

I get a linker error:

_/usr/bin/ld: sequence/libsequence.a(TsSequenceManager.cc.o): in function `TsSequenceManager::TsSequenceManager(TsParameterManager*, TsExtensionManager*, TsMaterialManager*, TsGeometryManager*, TsPhysicsManager*, TsVarianceManager*, TsFilterManager*, TsScoringManager*, TsGraphicsManager*, TsChemistryManager*, TsSourceManager*, int, char**)':
TsSequenceManager.cc:(.text+0xd117): undefined reference to `TsQt5::TsQt5(TsParameterManager*, TsExtensionManager*, TsMaterialManager*, TsGeometryManager*, TsScoringManager*, TsSequenceManager*, TsGraphicsManager*, TsSourceManager*)'
/usr/bin/ld: sequence/libsequence.a(TsSequenceManager.cc.o): in function `TsSequenceManager::AbortSession(int)':
TsSequenceManager.cc:(.text+0x11c6): undefined reference to `TsQt5::AbortSession()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/topas.dir/build.make:177: topas] Error 1
make[1]: *** [CMakeFiles/Makefile2:400: CMakeFiles/topas.dir/all] Error 2
make: *** [Makefile:166: all] Error 2_

There appears to be some issues with an undefined reference "TsQt5". This is repeatable using WSL, ubuntu & debian. Also tested multiple versions (Testing, Main, Release 4.2 and Release 4.1.1) and saw the same issue.

I also attempted to modify the command with:

 _cmake ../OpenTOPAS -DCMAKE_INSTALL_PREFIX=../OpenTOPAS-install -DTOPAS_USE_QT=ON -DTOPAS_USE_QT6=ON_

make -j14 install

It returns the same error:

_/usr/bin/ld: sequence/libsequence.a(TsQt6.cc.o): in function `TsQt6::UpdateParameterEditor()':
TsQt6.cc:(.text+0x9a9f): undefined reference to `TsQt6::staticMetaObject'
/usr/bin/ld: sequence/libsequence.a(TsQt6.cc.o): in function `TsQt6::TsQt6(TsParameterManager*, TsExtensionManager*, TsMaterialManager*, TsGeometryManager*, TsScoringManager*, TsSequenceManager*, TsGraphicsManager*, TsSourceManager*)':
TsQt6.cc:(.text+0xff77): undefined reference to `vtable for TsQt6'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/topas.dir/build.make:177: topas] Error 1
make[1]: *** [CMakeFiles/Makefile2:400: CMakeFiles/topas.dir/all] Error 2
make: *** [Makefile:166: all] Error 2_

Any ideas why this is happening, or if there was compiler issue with the new release this week?

**Comment by JoseRamosMendez** [comment]
Hi there
Depending whether you are using QT5 or QT6, now you must use -DTOPAS_USE_QT=ON -DTOPAS_USE_QT6=OFF for QT5, and -DTOPAS_USE_QT=ON -DTOPAS_USE_QT6=ON for QT6; and also the -DCMAKE_PREFIX_PATH pointing to your Qt installation. See the Quick Install Guides for current releases 
Best
